name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - name: Push Docker image
      run: |
        docker build -f HBD.HealthZ.UI/Dockerfile -t baoduy2412/healthz-ui:latest ./HBD.HealthZ.UI
        docker login -u baoduy2412 -p ${{ secrets.DOCKER_TOKEN }}
        docker push baoduy2412/healthz-ui:latest
